#!/bin/sh

sudo chown 0:0 /var/jb/Library/LaunchDaemons/com.julioverne.screendumpd.plist
sudo chmod 0644 /var/jb/Library/LaunchDaemons/com.julioverne.screendumpd.plist

sudo launchctl unload /var/jb/Library/LaunchDaemons/com.julioverne.screendumpd.plist
sudo launchctl load /var/jb/Library/LaunchDaemons/com.julioverne.screendumpd.plist

exit 0;
