# Based on https://github.com/Randomblock1/theos-action
name: Build Packages

on:
  workflow_dispatch

jobs:
  build:
    env:
      THEOS: /home/runner/theos
    runs-on: ubuntu-latest
    steps:

    - name: Install Deps
      shell: bash
      run: |
          sudo apt update -yq && sudo apt install libplist-dev libplist-utils libz3-dev -yq

    - name: Install Theos
      shell: bash
      run: |
        if [ ! -d "$THEOS" ]; then
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "Theos successfully downloaded."
          mkdir -p "$THEOS/lib/iphone/rootless"

          # New versions of theos seem to have issues compiling on Linux: https://gist.github.com/Serena1432/10763b73c8bcfa8c2d203c759a56b089#installing-theos

          cd "$THEOS"
          git checkout e045ac7
          git submodule update --init --recursive

        else
          echo "Theos already cached."
        fi

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build packages
      run: |
        cd screendump
        make clean && make package

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: "com.julioverne.screendump_iphoneos-arm64"
        path: ${{ github.workspace }}/screendump/packages/*.deb
